# Generated by Django 4.1.7 on 2023-04-18 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=42069)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42069)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TASchedulerWebApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42069)),
                ('password', models.CharField(max_length=42069)),
            ],
        ),
        migrations.CreateModel(
            name='LabSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TASchedulerWebApp.section')),
            ],
            bases=('TASchedulerWebApp.section',),
        ),
        migrations.CreateModel(
            name='LectureSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TASchedulerWebApp.section')),
            ],
            bases=('TASchedulerWebApp.section',),
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TASchedulerWebApp.user')),
            ],
            bases=('TASchedulerWebApp.user',),
        ),
        migrations.AddField(
            model_name='course',
            name='sections',
            field=models.ManyToManyField(blank=True, to='TASchedulerWebApp.section'),
        ),
        migrations.CreateModel(
            name='TeacherAssistant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TASchedulerWebApp.user')),
                ('labSections', models.ManyToManyField(blank=True, to='TASchedulerWebApp.section')),
            ],
            bases=('TASchedulerWebApp.user',),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TASchedulerWebApp.user')),
                ('courses', models.ManyToManyField(blank=True, to='TASchedulerWebApp.course')),
            ],
            bases=('TASchedulerWebApp.user',),
        ),
    ]
