# Generated by Django 4.2 on 2023-04-25 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TASchedulerWebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('Instructor', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('Sections', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TASchedulerWebApp.section')),
            ],
        ),
    ]
