# Generated by Django 4.2 on 2023-04-27 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TASchedulerWebApp', '0002_remove_course_sections_section_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='email',
        ),
    ]
