# Generated by Django 4.2 on 2023-05-02 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TASchedulerWebApp', '0004_course_instructor_section_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='TeacherAssistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_teacher_assistant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='section',
            name='Instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_instructor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='section',
            name='TeacherAssistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_teacher_assistant', to=settings.AUTH_USER_MODEL),
        ),
    ]
