# Generated by Django 4.2 on 2023-05-02 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TASchedulerWebApp', '0005_course_teacherassistant_alter_section_instructor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='TeacherAssistant',
            new_name='teacher_assistant',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='Course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='Instructor',
            new_name='instructor',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Instructor',
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_instructor', to=settings.AUTH_USER_MODEL),
        ),
    ]
