# Generated by Django 4.2 on 2023-05-17 21:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TASchedulerWebApp', '0005_notification_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='TeacherAssistant',
        ),
        migrations.AddField(
            model_name='skill',
            name='TeacherAssistant',
            field=models.ManyToManyField(blank=True, related_name='skills', to=settings.AUTH_USER_MODEL),
        ),
    ]
