# Generated by Django 4.2 on 2023-05-02 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TASchedulerWebApp', '0006_rename_teacherassistant_course_teacher_assistant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='TeacherAssistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
