# Generated by Django 4.1.7 on 2023-05-14 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TASchedulerWebApp', '0007_alter_section_teacherassistant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher_assistant',
        ),
        migrations.RemoveField(
            model_name='section',
            name='TeacherAssistant',
        ),
        migrations.RemoveField(
            model_name='section',
            name='instructor',
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='courses_as_instructor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_assistants',
            field=models.ManyToManyField(blank=True, related_name='courses_as_teacher_assistant', to=settings.AUTH_USER_MODEL),
        ),
    ]
