# Generated by Django 4.1.7 on 2023-05-14 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TASchedulerWebApp', '0008_remove_course_instructor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TASchedulerWebApp.course')),
            ],
        ),
    ]
