from TASchedulerWebApp.tests.test_Section import *
from TASchedulerWebApp.tests.test_Skills import *
from TASchedulerWebApp.tests.test_Notification import *
from TASchedulerWebApp.tests.test_Accounts import *
from TASchedulerWebApp.tests.test_Directory import *
from TASchedulerWebApp.tests.test_AccountDelete import *
from TASchedulerWebApp.tests.test_Courses import *
from TASchedulerWebApp.tests.test_Login import *
from TASchedulerWebApp.tests.test_Assign import *