from TASchedulerWebApp.AcceptanceTests.test_Section import *
from TASchedulerWebApp.AcceptanceTests.test_Skills import *
from TASchedulerWebApp.AcceptanceTests.test_Notification import *
from TASchedulerWebApp.AcceptanceTests.test_Accounts import *
from TASchedulerWebApp.AcceptanceTests.test_Directory import *
from TASchedulerWebApp.AcceptanceTests.test_AccountDelete import *
from TASchedulerWebApp.AcceptanceTests.test_Courses import *
from TASchedulerWebApp.AcceptanceTests.test_Login import *
from TASchedulerWebApp.AcceptanceTests.test_Assign import *